config/urls.py
# url 꾸러미들.

from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views # pybo의 views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base_views.index,name='index'),
    path('common/',include('common.urls')),
    path('pybo/',include('pybo.urls')) # pybo/로 연결되는 endpoint는 전부 pybo.urls에서 가지고온다.
]

pybo/urls.py
from django.urls import path
from .views import base_views,question_views,answer_views,comment_views, vote_views

app_name = 'pybo' # pybo의 namespace

urlpatterns = [
    # path('',views.index),
    # path('<int:question_id>/', views.detail),  # 가변적인 endpoint, question.id의 타입은 int이다.
    #base_views
    path('',base_views.index, name = 'index'),
    path('<int:question_id>/', base_views.detail,name = 'detail'),

    #question_views
    path('question/create/', question_views.question_create,name = 'question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name = 'question_delete'),

    #answer_views
    path('answer/create/<int:question_id>/',answer_views.answer_create,name = 'answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),

    #comment_views
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name = 'comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name = 'comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name = 'comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name = 'comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name = 'comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name = 'comment_delete_answer'),
    path('vote/question/<int:question_id>',vote_views.vote_question,name = 'vote_question'),
    path('vote/answer/<int:answer_id>',vote_views.vote_answer,name = 'vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User  # 회원가입 모델


# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)  # 글자 수 제한하려면 charField
    content = models.TextField()  # 글자수 제한 X
    create_date = models.DateTimeField()  # 시간
    modify_date = models.DateTimeField(null=True, blank=True)  # blank = True 로 form.is_valid에서 오류 X
    author = models.ForeignKey(User, on_delete=models.CASCADE,  # 작성자는 User를 외래키로 받음.
                               related_name='author_question')
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):  # Question.objects.all에 보기 편한 format
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 질문에 대한 답변이므로 foreinkey , 질문과 함께 삭제
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_answer')
    voter = models.ManyToManyField(User, related_name='voter_answer')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from pybo.models import Question,Answer,Comment

class QuestionForm(forms.ModelForm): # forms.ModelForm을 상속받은 모델 폼
    class Meta: # 장고 모델폼은 Meta 내부 클래스를 반드시 포함해야함. 모델 폼이 사용할 모델과 필드를 작성.
        model = Question
        fields = ['subject','content']
        labels = {
            'subject':'제목',
            'content':'내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변 내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글 내용'
        }

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404,redirect, resolve_url # 404일 경우 ,페이지 이동
from ..models import Question,Answer
from django.utils import timezone
from ..forms import AnswerForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='common:login')
def answer_create(request, question_id):
    '''
    pybo 답변 등록
    '''
    question = get_object_or_404(Question,pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question_id),answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)



@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    '''
    답변 수정
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'
                            .format(resolve_url('pybo:detail', question_id=answer.question.id),answer.id)) #  resolve_url ==> 반환되는 url을 문자열로 만들어줌.
    else:
        form = AnswerForm(instance=answer)
    context = {'form':form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    '''
    답변 삭제
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    else:
        answer.delete()
    return redirect('pybo:index')

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from ..models import Question
from django.db.models import Q, Count

def index(request):  # 초기화면
    '''
    pybo 목록 출력
    '''
    page = request.GET.get('page', 1)  # 페이지 / GET방식으로 page를 파라미터로 가져올 때 사용, 파라미터 없이 들어올 때 dafault값을 1로 줌.
    kw = request.GET.get('kw','')  # 검색 / 없어도 됨
    so = request.GET.get('so', 'recent')
    # 조회
    if so == 'recommend':
        question_list = Question.objects.annotate(
            num_voter = Count('voter')).order_by('-num_voter','create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(
            num_answer = Count('answer')).order_by('-num_answer','create_date')
    else :
        question_list = Question.objects.order_by('-create_date')  # -로 역순

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # 페이징
    paginator = Paginator(question_list,10)  # 한 페이지당 개수
    page_obj = paginator.get_page(page)  # html에 전달할 객

    context = {'question_list': page_obj, 'page': page, 'kw': kw,'so':so}
    # return HttpResponse('Hi pybo') # Hi pybo를 response해라
    return render(request,'pybo/question_list.html',context)



def detail(request,question_id):  # 질문 상세 화면
    '''
    pybo 내용 출력
    '''
    # question = Question.objects.get(id = question_id)
    page = request.GET.get('page',1)
    question = get_object_or_404(Question, pk=question_id)  # Qustion 모델에서 get으로 전달받은 question_id가 없으면 404 발생시킴
    answer_list = question.answer_set.all().annotate(num_voter = Count('voter')).order_by('-num_voter')
    paginator = Paginator(answer_list,5)
    page_obj = paginator.get_page(page)
    context = {'question': question,'answer_list':page_obj,'page':page}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.shortcuts import render, get_object_or_404,redirect, resolve_url  # 404일 경우 ,페이지 이동
from ..models import Question,Answer,Comment
from django.utils import timezone
from ..forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='common:login')
def comment_create_question(request,question_id):
    '''
    pybo 질문 댓글 등록
    '''
    question = get_object_or_404(Question,pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():  # form이 유효한지 검증
            comment = form.save(commit=False)  # form에 create_date이 없으므로 여기서 저장하면 에러발생!
            comment.author = request.user
            comment.create_date = timezone.now()  # create_date를 넣어주고 저장
            comment.question = question
            comment.save()
            return redirect('{}#answer_{}'
                            .format(resolve_url('pybo:detail', question_id=comment.question.id),
                                    comment.id))
    else:
        form = CommentForm()            # method가 GET인 경우
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    '''
    댓글 수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#answer_{}'
                            .format(resolve_url('pybo:detail', question_id=comment.question.id),
                                    comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request,'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request,comment_id):
    '''
    댓글 삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request,answer_id):
    '''
    답변 댓글 등록
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():  # form이 유효한지 검증
            comment = form.save(commit=False)  # form에 create_date이 없으므로 여기서 저장하면 에러발생!
            comment.author = request.user
            comment.create_date = timezone.now()  # create_date를 넣어주고 저장
            comment.answer = answer
            comment.save()
            return redirect('{}#answer_{}'
                            .format(resolve_url('pybo:detail', question_id=comment.answer.question.id),
                                    comment.id))
    else:
        form = CommentForm()  # method가 GET인 경우
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request,comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#answer_{}'
                            .format(resolve_url('pybo:detail', question_id=comment.answer.question.id),
                                    comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.shortcuts import render, get_object_or_404,redirect # 404일 경우 ,페이지 이동
from ..models import Question
from django.utils import timezone
from ..forms import QuestionForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='common:login')
def question_create(request):  # 질문 작성
    '''
    pybo 질문 등록
    '''
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():  # form이 유효한지 검증 == 빈 값이 있는지 확인
            question = form.save(commit=False)  # form에 create_date이 없으므로 여기서 저장하면 에러발생!
            question.author = request.user
            question.create_date = timezone.now()  # create_date를 넣어주고 저장
            question.save()
            return redirect('pybo:index')  # index는 초기화면이다
    else:
        form = QuestionForm()            # method가 GET인 경우 미리 정의해둔 Question_Form을 전달
    context = {'form':form}
    return render(request,'pybo/question_form.html',context)


@login_required(login_url='common:login')
def question_modify(request,question_id):
    '''
    질문 수정
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)

    if request.method == 'POST':
        form = QuestionForm(request.POST,instance=question)  # 수정시에 있는걸보니 QuestionForm에 question 안에 값을 그대로 넘겨주는 듯.
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request,'pybo/question_form.html',context)

@login_required(login_url='common:login')
def question_delete(request,question_id):
    '''
    질문 삭제
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question,Answer

@login_required(login_url='common:login')
def vote_question(request,question_id):
    '''
    질문 추천
    '''
    question = get_object_or_404(Question,pk=question_id)
    if request.user == question.author:
        messages.error(request,'본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail',question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request,answer_id):
    '''
    질문 추천
    '''
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user == answer.author:
        messages.error(request,'본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail',question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-gorup">
            <label for="content">댓글 내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="3">{{ from.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
<!--    사용자 오류 표시-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"><!-- 추천 영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ question.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
<!--            기존 내용-->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn-sm btn-outline-secondary"
                        data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--질문 댓글 시작-->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                            <a name="comment_{{ comment.id }}"></a>
                            <div class="comment py-2 text-muted">
                                <span style="white-space: pre-line;">{{ comment.content }}</span>
                                <span>
                                    - {{ comment.author }}, {{ comment.create_date }}
                                    {% if comment.modify_date %}
                                    (수정 : {{ comment.modify_date }}
                                    {% endif %}
                                </span>
                                {% if request.user == comment.author %}
                                <a href="{% url 'pybo:comment_modify_question' comment.id %}"
                                   class="small">수정</a>,
                                <a href="#" class="small delete"
                                   data-uri="{% url 'pybo:comment_delete_question' comment.id %}">
                                    삭제
                                </a>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id %}"
                           class="small"><small>댓글 추가</small></a>
                    </div>
                    <!--질문 댓글 끝-->
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in answer_list %}
    <a name="answer_{{ answer.id }}"></a> <!-- 앵커 엘리먼트 ( 해당 위치로 스크롤 이동 )-->
    <div class="row my-3">
        <div class="col-1"> <!--        추천영역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ answer.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}"
            class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
    <div class="col-11">
        <div class="card"> <!-- 답변 영역-->
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ question.author.username }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                {% if request.user == answer.author %}
                <div class="my-3">
                    <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn-sm btn-outline-secondary"
                    data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                </div>
                {% endif %}
    <!--            답변 댓글 시작-->
                {% if answer.comment_set.count > 0 %}
                <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }} , {{ comment.create_date }}
                                {% if comment.modify_date %}
                                ( 수정 : {{comment.modify_date }} )
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>,
                            <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                        </div>

                    {% endfor %}
                </div>
                {% endif %}
                <div>
                    <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small"><small>댓글 추가</small></a>
                </div>
    <!--            답변 댓글 끝-->
               </div>
             </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
<!--        답변 페이징-->
        <ul class="pagination justify-content-center">
            {% if answer_list.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   data-page="{{ answer_list.previous_page_number }}"
                   href="#">
                    이전
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                    이전
                </a>
            </li>
            {% endif %}
            {% if answer_list.has_next %}
            <li class="page-item">
                <a class="page-link"
                   data-page="{{ answer_list.next_page_number }}" href="#">
                    다음
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                    다음
                </a>
            </li>
            {% endif %}
        </ul>
        <div class="form-group">
            <textarea name="content" id="content"
                      {% if not user.is_authenticated %}disabled{% endif %}
                      class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
<form id="searchForm" method="get" action="{% url 'pybo:detail' question.id %}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function(){
        if(confirm("정말로 추천하시겠습니까?")){
            location.href = $(this).data('uri');
        }
    });
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                    value="{{ form.subject.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:''}}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}