common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(
        template_name = 'common/login.html'),name = 'login'), # 장고 auth앱의 loginview를 활용하므로 별도의 기능추가가 필요없음.
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup, name = 'signup'),
]

config/urls.py
# url 꾸러미들.

from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views # pybo의 views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base_views.index,name='index'),
    path('common/',include('common.urls')),
    path('pybo/',include('pybo.urls')) # pybo/로 연결되는 endpoint는 전부 pybo.urls에서 가지고온다.
]

pybo/urls.py
from django.urls import path
from .views import base_views,question_views,answer_views,comment_views, vote_views

app_name = 'pybo' # pybo의 namespace

urlpatterns = [
    # path('',views.index),
    # path('<int:question_id>/', views.detail),  # 가변적인 endpoint, question.id의 타입은 int이다.
    #base_views
    path('',base_views.index, name = 'index'),
    path('<int:question_id>/', base_views.detail,name = 'detail'),

    #question_views
    path('question/create/', question_views.question_create,name = 'question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name = 'question_delete'),

    #answer_views
    path('answer/create/<int:question_id>/',answer_views.answer_create,name = 'answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),

    #comment_views
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name = 'comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name = 'comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name = 'comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name = 'comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name = 'comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name = 'comment_delete_answer'),
    path('vote/question/<int:question_id>',vote_views.vote_question,name = 'vote_question'),
    path('vote/answer/<int:answer_id>',vote_views.vote_answer,name = 'vote_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from ..models import Question
from django.db.models import Q, Count

def index(request):  # 초기화면
    '''
    pybo 목록 출력
    '''
    page = request.GET.get('page', 1)  # 페이지 / GET방식으로 page를 파라미터로 가져올 때 사용, 파라미터 없이 들어올 때 dafault값을 1로 줌.
    kw = request.GET.get('kw','')  # 검색 / 없어도 됨
    so = request.GET.get('so', 'recent')
    # 조회
    if so == 'recommend':
        question_list = Question.objects.annotate(
            num_voter = Count('voter')).order_by('-num_voter','create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(
            num_answer = Count('answer')).order_by('-num_answer','create_date')
    else :
        question_list = Question.objects.order_by('-create_date')  # -로 역순

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # 페이징
    paginator = Paginator(question_list,10)  # 한 페이지당 개수
    page_obj = paginator.get_page(page)  # html에 전달할 객

    context = {'question_list': page_obj, 'page': page, 'kw': kw,'so':so}
    # return HttpResponse('Hi pybo') # Hi pybo를 response해라
    return render(request,'pybo/question_list.html',context)



def detail(request,question_id):  # 질문 상세 화면
    '''
    pybo 내용 출력
    '''
    # question = Question.objects.get(id = question_id)
    page = request.GET.get('page',1)
    question = get_object_or_404(Question, pk=question_id)  # Qustion 모델에서 get으로 전달받은 question_id가 없으면 404 발생시킴
    answer_list = question.answer_set.all().annotate(num_voter = Count('voter')).order_by('-num_voter')
    paginator = Paginator(answer_list,5)
    page_obj = paginator.get_page(page)
    context = {'question': question,'answer_list':page_obj,'page':page}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!--네비게이션 바-->
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<!-- JQuery JS-->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!--Bootstrap JS-->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!--자바 스크립트-->
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!--네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flse-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">
                    {{ user.username }} (로그아웃)
                </a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>